name: run-unit-tests

# Only run this when there is a pull-request opened
on: push

jobs:
    run-unit-tests:
        runs-on: ubuntu-latest #needs to be an image that supports PowerShell
        steps:
        - uses: actions/checkout@v2
        
        # Install dependencies, right version of Pester, everything else should be Powershell native
        - name: Install dependencies
          run: |
            sudo apt-get update;
            sudo apt-get install -y wget apt-transport-https software-properties-common;
            wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb;
            sudo dpkg -i packages-microsoft-prod.deb;
            sudo apt-get update;
            sudo apt-get install -y powershell;
            pwsh ./tests/run_pester_install.ps1
        # Execute Pester Tests
        - name: Execute unit tests
          run: |
            pwsh ./tests/run_pester_tests.ps1;
